'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.17626
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServiceReferenceALP
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ResponceHistory", [Namespace]:="http://www.alp.ru/consolid/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ResponceHistory
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private TextField As String
        
        Private Data1Field() As Byte
        
        Private Data2Field() As Byte
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Text() As String
            Get
                Return Me.TextField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TextField, value) <> true) Then
                    Me.TextField = value
                    Me.RaisePropertyChanged("Text")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=1)>  _
        Public Property Data1() As Byte()
            Get
                Return Me.Data1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Data1Field, value) <> true) Then
                    Me.Data1Field = value
                    Me.RaisePropertyChanged("Data1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=2)>  _
        Public Property Data2() As Byte()
            Get
                Return Me.Data2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Data2Field, value) <> true) Then
                    Me.Data2Field = value
                    Me.RaisePropertyChanged("Data2")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.alp.ru/consolid/", ConfigurationName:="ServiceReferenceALP.ALP_OutlookServicesPortType")>  _
    Public Interface ALP_OutlookServicesPortType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.alp.ru/consolid/#ALP_OutlookServices:TestConnection", ReplyAction:="*")>  _
        Function TestConnection() As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Boolean
        
        'CODEGEN: Контракт генерации сообщений с именем IDProcess из пространства имен http://www.alp.ru/consolid/ не отмечен как обнуляемый
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.alp.ru/consolid/#ALP_OutlookServices:PutAgreement", ReplyAction:="*")>  _
        Function PutAgreement(ByVal request As ServiceReferenceALP.PutAgreementRequest) As ServiceReferenceALP.PutAgreementResponse
        
        'CODEGEN: Контракт генерации сообщений с именем IDProcess из пространства имен http://www.alp.ru/consolid/ не отмечен как обнуляемый
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.alp.ru/consolid/#ALP_OutlookServices:PutCancel", ReplyAction:="*")>  _
        Function PutCancel(ByVal request As ServiceReferenceALP.PutCancelRequest) As ServiceReferenceALP.PutCancelResponse
        
        'CODEGEN: Контракт генерации сообщений с именем IDProcess из пространства имен http://www.alp.ru/consolid/ не отмечен как обнуляемый
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.alp.ru/consolid/#ALP_OutlookServices:GetInfoAboutDocument", ReplyAction:="*")>  _
        Function GetInfoAboutDocument(ByVal request As ServiceReferenceALP.GetInfoAboutDocumentRequest) As ServiceReferenceALP.GetInfoAboutDocumentResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class PutAgreementRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="PutAgreement", [Namespace]:="http://www.alp.ru/consolid/", Order:=0)>  _
        Public Body As ServiceReferenceALP.PutAgreementRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReferenceALP.PutAgreementRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.alp.ru/consolid/")>  _
    Partial Public Class PutAgreementRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public IDProcess As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Text As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public DocType As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal IDProcess As String, ByVal Text As String, ByVal DocType As String)
            MyBase.New
            Me.IDProcess = IDProcess
            Me.Text = Text
            Me.DocType = DocType
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class PutAgreementResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="PutAgreementResponse", [Namespace]:="http://www.alp.ru/consolid/", Order:=0)>  _
        Public Body As ServiceReferenceALP.PutAgreementResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReferenceALP.PutAgreementResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.alp.ru/consolid/")>  _
    Partial Public Class PutAgreementResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class PutCancelRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="PutCancel", [Namespace]:="http://www.alp.ru/consolid/", Order:=0)>  _
        Public Body As ServiceReferenceALP.PutCancelRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReferenceALP.PutCancelRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.alp.ru/consolid/")>  _
    Partial Public Class PutCancelRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public IDProcess As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Text As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public DocType As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal IDProcess As String, ByVal Text As String, ByVal DocType As String)
            MyBase.New
            Me.IDProcess = IDProcess
            Me.Text = Text
            Me.DocType = DocType
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class PutCancelResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="PutCancelResponse", [Namespace]:="http://www.alp.ru/consolid/", Order:=0)>  _
        Public Body As ServiceReferenceALP.PutCancelResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReferenceALP.PutCancelResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.alp.ru/consolid/")>  _
    Partial Public Class PutCancelResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetInfoAboutDocumentRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetInfoAboutDocument", [Namespace]:="http://www.alp.ru/consolid/", Order:=0)>  _
        Public Body As ServiceReferenceALP.GetInfoAboutDocumentRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReferenceALP.GetInfoAboutDocumentRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.alp.ru/consolid/")>  _
    Partial Public Class GetInfoAboutDocumentRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public IDProcess As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public DocType As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal IDProcess As String, ByVal DocType As String)
            MyBase.New
            Me.IDProcess = IDProcess
            Me.DocType = DocType
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetInfoAboutDocumentResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetInfoAboutDocumentResponse", [Namespace]:="http://www.alp.ru/consolid/", Order:=0)>  _
        Public Body As ServiceReferenceALP.GetInfoAboutDocumentResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReferenceALP.GetInfoAboutDocumentResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.alp.ru/consolid/")>  _
    Partial Public Class GetInfoAboutDocumentResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public [return] As ServiceReferenceALP.ResponceHistory
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As ServiceReferenceALP.ResponceHistory)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ALP_OutlookServicesPortTypeChannel
        Inherits ServiceReferenceALP.ALP_OutlookServicesPortType, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ALP_OutlookServicesPortTypeClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReferenceALP.ALP_OutlookServicesPortType)
        Implements ServiceReferenceALP.ALP_OutlookServicesPortType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function TestConnection() As Boolean Implements ServiceReferenceALP.ALP_OutlookServicesPortType.TestConnection
            Return MyBase.Channel.TestConnection
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReferenceALP_ALP_OutlookServicesPortType_PutAgreement(ByVal request As ServiceReferenceALP.PutAgreementRequest) As ServiceReferenceALP.PutAgreementResponse Implements ServiceReferenceALP.ALP_OutlookServicesPortType.PutAgreement
            Return MyBase.Channel.PutAgreement(request)
        End Function
        
        Public Function PutAgreement(ByVal IDProcess As String, ByVal Text As String, ByVal DocType As String) As String
            Dim inValue As ServiceReferenceALP.PutAgreementRequest = New ServiceReferenceALP.PutAgreementRequest()
            inValue.Body = New ServiceReferenceALP.PutAgreementRequestBody()
            inValue.Body.IDProcess = IDProcess
            inValue.Body.Text = Text
            inValue.Body.DocType = DocType
            Dim retVal As ServiceReferenceALP.PutAgreementResponse = CType(Me,ServiceReferenceALP.ALP_OutlookServicesPortType).PutAgreement(inValue)
            Return retVal.Body.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReferenceALP_ALP_OutlookServicesPortType_PutCancel(ByVal request As ServiceReferenceALP.PutCancelRequest) As ServiceReferenceALP.PutCancelResponse Implements ServiceReferenceALP.ALP_OutlookServicesPortType.PutCancel
            Return MyBase.Channel.PutCancel(request)
        End Function
        
        Public Function PutCancel(ByVal IDProcess As String, ByVal Text As String, ByVal DocType As String) As String
            Dim inValue As ServiceReferenceALP.PutCancelRequest = New ServiceReferenceALP.PutCancelRequest()
            inValue.Body = New ServiceReferenceALP.PutCancelRequestBody()
            inValue.Body.IDProcess = IDProcess
            inValue.Body.Text = Text
            inValue.Body.DocType = DocType
            Dim retVal As ServiceReferenceALP.PutCancelResponse = CType(Me,ServiceReferenceALP.ALP_OutlookServicesPortType).PutCancel(inValue)
            Return retVal.Body.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReferenceALP_ALP_OutlookServicesPortType_GetInfoAboutDocument(ByVal request As ServiceReferenceALP.GetInfoAboutDocumentRequest) As ServiceReferenceALP.GetInfoAboutDocumentResponse Implements ServiceReferenceALP.ALP_OutlookServicesPortType.GetInfoAboutDocument
            Return MyBase.Channel.GetInfoAboutDocument(request)
        End Function
        
        Public Function GetInfoAboutDocument(ByVal IDProcess As String, ByVal DocType As String) As ServiceReferenceALP.ResponceHistory
            Dim inValue As ServiceReferenceALP.GetInfoAboutDocumentRequest = New ServiceReferenceALP.GetInfoAboutDocumentRequest()
            inValue.Body = New ServiceReferenceALP.GetInfoAboutDocumentRequestBody()
            inValue.Body.IDProcess = IDProcess
            inValue.Body.DocType = DocType
            Dim retVal As ServiceReferenceALP.GetInfoAboutDocumentResponse = CType(Me,ServiceReferenceALP.ALP_OutlookServicesPortType).GetInfoAboutDocument(inValue)
            Return retVal.Body.[return]
        End Function
    End Class
End Namespace
