'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.17626
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReferenceALP
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.alp.ru/bdks/", ConfigurationName:="ServiceReferenceALP.ALP_OutlookServicesPortType")>  _
    Public Interface ALP_OutlookServicesPortType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.alp.ru/bdks/#ALP_OutlookServices:GetProcessHistory", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetProcessHistory(ByVal IDProcess As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServiceReferenceALP.ResponceHistory
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.alp.ru/bdks/#ALP_OutlookServices:GetAttachmentFromBisnessProcess", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetAttachmentFromBisnessProcess(ByVal IDProcess As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServiceReferenceALP.ResponceAttachments
        
        'CODEGEN: Параметр "ArrayAttachments" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlArrayItemAttribute".
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.alp.ru/bdks/#ALP_OutlookServices:ReturnAttachmentToBisnessProcess", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ReturnAttachmentToBisnessProcess(ByVal request As ServiceReferenceALP.ReturnAttachmentToBisnessProcessRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServiceReferenceALP.ReturnAttachmentToBisnessProcessResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.alp.ru/bdks/#ALP_OutlookServices:PutAgreement", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function PutAgreement(ByVal IDProcess As String, ByVal Text As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.alp.ru/bdks/#ALP_OutlookServices:PutCancel", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function PutCancel(ByVal IDProcess As String, ByVal Text As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> String
        
        'CODEGEN: Параметр "ArrayAttachments" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlArrayItemAttribute".
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.alp.ru/bdks/#ALP_OutlookServices:LockDocumentsInBisnessProcess", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function LockDocumentsInBisnessProcess(ByVal request As ServiceReferenceALP.LockDocumentsInBisnessProcessRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServiceReferenceALP.LockDocumentsInBisnessProcessResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.alp.ru/bdks/#ALP_OutlookServices:CreateProcess", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CreateProcess(ByVal Process As ServiceReferenceALP.Process) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServiceReferenceALP.ResponceCreateProcess
        
        'CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlArrayItemAttribute".
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.alp.ru/bdks/#ALP_OutlookServices:GetUserList", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetUserList(ByVal request As ServiceReferenceALP.GetUserListRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServiceReferenceALP.GetUserListResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.alp.ru/bdks/#ALP_OutlookServices:TestConnection", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function TestConnection() As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Boolean
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17626"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.alp.ru/bdks/")>  _
    Partial Public Class ResponceHistory
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private textField As String
        
        Private dataField() As Byte
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property Text() As String
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
                Me.RaisePropertyChanged("Text")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", IsNullable:=true, Order:=1)>  _
        Public Property Data() As Byte()
            Get
                Return Me.dataField
            End Get
            Set
                Me.dataField = value
                Me.RaisePropertyChanged("Data")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17626"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.alp.ru/bdks/")>  _
    Partial Public Class User
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private nameField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
                Me.RaisePropertyChanged("Name")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17626"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.alp.ru/bdks/")>  _
    Partial Public Class ResponceCreateProcess
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private textField As String
        
        Private statusField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property Text() As String
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
                Me.RaisePropertyChanged("Text")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("Status")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17626"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.alp.ru/bdks/")>  _
    Partial Public Class Process
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private subjectField As String
        
        Private detailTextField As String
        
        Private arrayAttachmentField() As BinaryFile
        
        Private taskForField As String
        
        Private deadLineField As String
        
        Private importanceField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property Subject() As String
            Get
                Return Me.subjectField
            End Get
            Set
                Me.subjectField = value
                Me.RaisePropertyChanged("Subject")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property DetailText() As String
            Get
                Return Me.detailTextField
            End Get
            Set
                Me.detailTextField = value
                Me.RaisePropertyChanged("DetailText")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true, Order:=2),  _
         System.Xml.Serialization.XmlArrayItemAttribute("Data")>  _
        Public Property ArrayAttachment() As BinaryFile()
            Get
                Return Me.arrayAttachmentField
            End Get
            Set
                Me.arrayAttachmentField = value
                Me.RaisePropertyChanged("ArrayAttachment")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=3)>  _
        Public Property TaskFor() As String
            Get
                Return Me.taskForField
            End Get
            Set
                Me.taskForField = value
                Me.RaisePropertyChanged("TaskFor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=4)>  _
        Public Property DeadLine() As String
            Get
                Return Me.deadLineField
            End Get
            Set
                Me.deadLineField = value
                Me.RaisePropertyChanged("DeadLine")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property Importance() As String
            Get
                Return Me.importanceField
            End Get
            Set
                Me.importanceField = value
                Me.RaisePropertyChanged("Importance")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17626"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.alp.ru/bdks/")>  _
    Partial Public Class BinaryFile
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private fileNameField As String
        
        Private fileExtensionField As String
        
        Private fileDataSizeField As String
        
        Private fileDateModifiedField As String
        
        Private fileDataField() As Byte
        
        Private fileCustomTextField As String
        
        Private fileLockedCurrentUserField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property FileName() As String
            Get
                Return Me.fileNameField
            End Get
            Set
                Me.fileNameField = value
                Me.RaisePropertyChanged("FileName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property FileExtension() As String
            Get
                Return Me.fileExtensionField
            End Get
            Set
                Me.fileExtensionField = value
                Me.RaisePropertyChanged("FileExtension")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer", IsNullable:=true, Order:=2)>  _
        Public Property FileDataSize() As String
            Get
                Return Me.fileDataSizeField
            End Get
            Set
                Me.fileDataSizeField = value
                Me.RaisePropertyChanged("FileDataSize")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=3)>  _
        Public Property FileDateModified() As String
            Get
                Return Me.fileDateModifiedField
            End Get
            Set
                Me.fileDateModifiedField = value
                Me.RaisePropertyChanged("FileDateModified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", IsNullable:=true, Order:=4)>  _
        Public Property FileData() As Byte()
            Get
                Return Me.fileDataField
            End Get
            Set
                Me.fileDataField = value
                Me.RaisePropertyChanged("FileData")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=5)>  _
        Public Property FileCustomText() As String
            Get
                Return Me.fileCustomTextField
            End Get
            Set
                Me.fileCustomTextField = value
                Me.RaisePropertyChanged("FileCustomText")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=6)>  _
        Public Property FileLockedCurrentUser() As String
            Get
                Return Me.fileLockedCurrentUserField
            End Get
            Set
                Me.fileLockedCurrentUserField = value
                Me.RaisePropertyChanged("FileLockedCurrentUser")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17626"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.alp.ru/bdks/")>  _
    Partial Public Class ResponceAttachments
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private textField As String
        
        Private dataField() As BinaryFile
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property Text() As String
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
                Me.RaisePropertyChanged("Text")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Data", IsNullable:=true, Order:=1)>  _
        Public Property Data() As BinaryFile()
            Get
                Return Me.dataField
            End Get
            Set
                Me.dataField = value
                Me.RaisePropertyChanged("Data")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ReturnAttachmentToBisnessProcess", WrapperNamespace:="http://www.alp.ru/bdks/", IsWrapped:=true)>  _
    Partial Public Class ReturnAttachmentToBisnessProcessRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.alp.ru/bdks/", Order:=0)>  _
        Public IDProcess As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.alp.ru/bdks/", Order:=1),  _
         System.Xml.Serialization.XmlArrayItemAttribute("Data")>  _
        Public ArrayAttachments() As ServiceReferenceALP.BinaryFile
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal IDProcess As String, ByVal ArrayAttachments() As ServiceReferenceALP.BinaryFile)
            MyBase.New
            Me.IDProcess = IDProcess
            Me.ArrayAttachments = ArrayAttachments
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ReturnAttachmentToBisnessProcessResponse", WrapperNamespace:="http://www.alp.ru/bdks/", IsWrapped:=true)>  _
    Partial Public Class ReturnAttachmentToBisnessProcessResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.alp.ru/bdks/", Order:=0)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="LockDocumentsInBisnessProcess", WrapperNamespace:="http://www.alp.ru/bdks/", IsWrapped:=true)>  _
    Partial Public Class LockDocumentsInBisnessProcessRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.alp.ru/bdks/", Order:=0)>  _
        Public IDProcess As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.alp.ru/bdks/", Order:=1),  _
         System.Xml.Serialization.XmlArrayItemAttribute("Data")>  _
        Public ArrayAttachments() As ServiceReferenceALP.BinaryFile
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal IDProcess As String, ByVal ArrayAttachments() As ServiceReferenceALP.BinaryFile)
            MyBase.New
            Me.IDProcess = IDProcess
            Me.ArrayAttachments = ArrayAttachments
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="LockDocumentsInBisnessProcessResponse", WrapperNamespace:="http://www.alp.ru/bdks/", IsWrapped:=true)>  _
    Partial Public Class LockDocumentsInBisnessProcessResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.alp.ru/bdks/", Order:=0)>  _
        Public [return] As ServiceReferenceALP.ResponceAttachments
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As ServiceReferenceALP.ResponceAttachments)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetUserList", WrapperNamespace:="http://www.alp.ru/bdks/", IsWrapped:=true)>  _
    Partial Public Class GetUserListRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.alp.ru/bdks/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Name As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Name As String)
            MyBase.New
            Me.Name = Name
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetUserListResponse", WrapperNamespace:="http://www.alp.ru/bdks/", IsWrapped:=true)>  _
    Partial Public Class GetUserListResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.alp.ru/bdks/", Order:=0),  _
         System.Xml.Serialization.XmlArrayItemAttribute("Users")>  _
        Public [return]() As ServiceReferenceALP.User
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return]() As ServiceReferenceALP.User)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ALP_OutlookServicesPortTypeChannel
        Inherits ServiceReferenceALP.ALP_OutlookServicesPortType, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ALP_OutlookServicesPortTypeClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReferenceALP.ALP_OutlookServicesPortType)
        Implements ServiceReferenceALP.ALP_OutlookServicesPortType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetProcessHistory(ByVal IDProcess As String) As ServiceReferenceALP.ResponceHistory Implements ServiceReferenceALP.ALP_OutlookServicesPortType.GetProcessHistory
            Return MyBase.Channel.GetProcessHistory(IDProcess)
        End Function
        
        Public Function GetAttachmentFromBisnessProcess(ByVal IDProcess As String) As ServiceReferenceALP.ResponceAttachments Implements ServiceReferenceALP.ALP_OutlookServicesPortType.GetAttachmentFromBisnessProcess
            Return MyBase.Channel.GetAttachmentFromBisnessProcess(IDProcess)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReferenceALP_ALP_OutlookServicesPortType_ReturnAttachmentToBisnessProcess(ByVal request As ServiceReferenceALP.ReturnAttachmentToBisnessProcessRequest) As ServiceReferenceALP.ReturnAttachmentToBisnessProcessResponse Implements ServiceReferenceALP.ALP_OutlookServicesPortType.ReturnAttachmentToBisnessProcess
            Return MyBase.Channel.ReturnAttachmentToBisnessProcess(request)
        End Function
        
        Public Function ReturnAttachmentToBisnessProcess(ByVal IDProcess As String, ByVal ArrayAttachments() As ServiceReferenceALP.BinaryFile) As String
            Dim inValue As ServiceReferenceALP.ReturnAttachmentToBisnessProcessRequest = New ServiceReferenceALP.ReturnAttachmentToBisnessProcessRequest()
            inValue.IDProcess = IDProcess
            inValue.ArrayAttachments = ArrayAttachments
            Dim retVal As ServiceReferenceALP.ReturnAttachmentToBisnessProcessResponse = CType(Me,ServiceReferenceALP.ALP_OutlookServicesPortType).ReturnAttachmentToBisnessProcess(inValue)
            Return retVal.[return]
        End Function
        
        Public Function PutAgreement(ByVal IDProcess As String, ByVal Text As String) As String Implements ServiceReferenceALP.ALP_OutlookServicesPortType.PutAgreement
            Return MyBase.Channel.PutAgreement(IDProcess, Text)
        End Function
        
        Public Function PutCancel(ByVal IDProcess As String, ByVal Text As String) As String Implements ServiceReferenceALP.ALP_OutlookServicesPortType.PutCancel
            Return MyBase.Channel.PutCancel(IDProcess, Text)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReferenceALP_ALP_OutlookServicesPortType_LockDocumentsInBisnessProcess(ByVal request As ServiceReferenceALP.LockDocumentsInBisnessProcessRequest) As ServiceReferenceALP.LockDocumentsInBisnessProcessResponse Implements ServiceReferenceALP.ALP_OutlookServicesPortType.LockDocumentsInBisnessProcess
            Return MyBase.Channel.LockDocumentsInBisnessProcess(request)
        End Function
        
        Public Function LockDocumentsInBisnessProcess(ByVal IDProcess As String, ByVal ArrayAttachments() As ServiceReferenceALP.BinaryFile) As ServiceReferenceALP.ResponceAttachments
            Dim inValue As ServiceReferenceALP.LockDocumentsInBisnessProcessRequest = New ServiceReferenceALP.LockDocumentsInBisnessProcessRequest()
            inValue.IDProcess = IDProcess
            inValue.ArrayAttachments = ArrayAttachments
            Dim retVal As ServiceReferenceALP.LockDocumentsInBisnessProcessResponse = CType(Me,ServiceReferenceALP.ALP_OutlookServicesPortType).LockDocumentsInBisnessProcess(inValue)
            Return retVal.[return]
        End Function
        
        Public Function CreateProcess(ByVal Process As ServiceReferenceALP.Process) As ServiceReferenceALP.ResponceCreateProcess Implements ServiceReferenceALP.ALP_OutlookServicesPortType.CreateProcess
            Return MyBase.Channel.CreateProcess(Process)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReferenceALP_ALP_OutlookServicesPortType_GetUserList(ByVal request As ServiceReferenceALP.GetUserListRequest) As ServiceReferenceALP.GetUserListResponse Implements ServiceReferenceALP.ALP_OutlookServicesPortType.GetUserList
            Return MyBase.Channel.GetUserList(request)
        End Function
        
        Public Function GetUserList(ByVal Name As String) As ServiceReferenceALP.User()
            Dim inValue As ServiceReferenceALP.GetUserListRequest = New ServiceReferenceALP.GetUserListRequest()
            inValue.Name = Name
            Dim retVal As ServiceReferenceALP.GetUserListResponse = CType(Me,ServiceReferenceALP.ALP_OutlookServicesPortType).GetUserList(inValue)
            Return retVal.[return]
        End Function
        
        Public Function TestConnection() As Boolean Implements ServiceReferenceALP.ALP_OutlookServicesPortType.TestConnection
            Return MyBase.Channel.TestConnection
        End Function
    End Class
End Namespace
